import React from 'react'
import { Feature, motion } from 'framer-motion'
import { FcGoogle } from "react-icons/fc";
import { auth, provider } from '../utils/firebase.js';
import { signInWithPopup } from 'firebase/auth';
import axios from 'axios';
import { serverURL } from '../App.jsx';
import { useDispatch } from 'react-redux';
import { setUserData } from '../redux/userSlice';

function Auth() {
const dispatch = useDispatch();
    const handleGoogleSignIn = async () => {
        try {
            const response = await signInWithPopup(auth, provider);
            const User = response.user;
            const name = User.displayName;
            const email = User.email;
            const result = await axios.post(serverURL + "/api/auth/google", { name, email }, {withCredentials: true });

            dispatch(setUserData(result.data.user));
        } catch (error) {
            console.log(error);
        }
        }
    return (
        <div className='min-h-screen overflow-hidden bg-white text-black px-4 py-8'>
            <motion.header
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 1.5 }}
                className='max-w-7xl mx-auto mt-8
      rounded-2xl
      bg-black/80 backdrop-blur-xl
      border border-white/10
      px-8 py-6
      shadow-[0_20px_40px_-10px_rgba(0,0,0,0.5)]'>
                <h1 className='text-2xl font-bold text-center text-white'>Welcome to ExamNotesAI</h1>
                <p className='text-center text-white/80 mt-4'>Please sign in to access your personalized notes and start preparing for your exams!</p>
            </motion.header>

            <main className='max-w-7xl mx-auto py-10 grid grid-col-1 lg:grid-cols-2 gap-20 items-center'>
                {/* LEFT CONTENT */}
                <motion.div
                    initial={{ opacity: 0, x: -60 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 1.5 }}>
                    <h1 className='text-5xl lg:text-6xl font-extrabold leading-tight bg-gradient-to-br from-black/90 via-black/60 to-black/90 bg-clip-text text-transparent'>
                        Unlock Smart <br /> AI Notes </h1>
                    <motion.button
                        onClick={handleGoogleSignIn}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        className='mt-8 px-6 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300  flex items-center gap-2 cursor-pointer'>
                        <FcGoogle size={22} /> Sign In with Google
                    </motion.button>

                    <p className='mt-6 max-w-xl text-lg bg-gradient-to-br from-gray-700 via-gray-500/80 to-gray-700 bg-clip-text text-transparent'>
                        You get <span className='font-bold text-blue-600'>50 free credits
                        </span> to create exam notes , project notes , graphs and download clean PDFs -- instantly using AI.
                    </p>
                    <p className='mt-4 max-w-xl text-lg bg-gradient-to-br from-gray-700 via-gray-500/80 to-gray-700 bg-clip-text text-transparent'>
                        Start with <span className='font-bold text-blue-600'>50 free credits</span> • Upgrade anytime for more credits and features!
                    </p>

                </motion.div>


                {/* RIGHT CONTENT */}
                <div className='grid grid-cols-1 sm:grid-cols-2 gap-8'>
                    <FeatureCard icon="🎁" title=" 50 Free Credits" description="Get 50 free credits to create exam notes, project notes, graphs." />
                    <FeatureCard icon="📗" title=" Exam Notes" description="High yield exam-oriented notes generated by AI." />
                    <FeatureCard icon="📊" title=" Graphs & Diagrams" description="Create clear graphs and diagrams for visual learning." />
                    <FeatureCard icon="📥" title=" PDF Downloads" description="Download your notes as clean, well-formatted PDFs." />
                </div>
            </main>
        </div>
    )
}

function FeatureCard({ title, description, icon }) {
    return (
        <motion.div
            whileHover={{ y: -12, rotateX: 8, rotateY: -8, scale: 1.05 }}
            transition={{ type: "spring", stiffness: 200, damping: 18 }}
            className='relative rounded-2xl p-6 bg-gradient-to-br from-black/90 via-black/80 to-black/90 text-white shadow-[0_30px_60px_-10px_rgba(0,0,0,0.5)] border border-white/10' style={{ transformStyle: "preserve-3d" }}>
            <div className='absolute inset-0 rounded-2xl bg-gradient-to-br from-white/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none' style={{ transform: "translateZ(1px)" }}/>
                <div className='relative z-10 ' style={{ transform: "translateZ(30px)" }}>
                    <div className='text-4xl mb-3'>{icon}</div>
                    <h3 className='text-lg font-semibold mb-2'>{title}</h3>
                    <p className='text-gray-400 text-sm leading-relaxed'>{description}</p>
                </div>

        </motion.div>
    )
}

export default Auth
